// PRJ566NCC-Team3-user-api/utils/icalHelper.js

const ics = require('ics');

function createEvent(itinerary) {
  const { name, from, to } = itinerary;
  const start = [
    from.getFullYear(),
    from.getMonth() + 1,
    from.getDate(),
    from.getHours(),
    from.getMinutes(),
  ];
  const end = [
    to.getFullYear(),
    to.getMonth() + 1,
    to.getDate(),
    to.getHours(),
    to.getMinutes(),
  ];

  const { error, value } = ics.createEvent({
    title: name,
    start,
    end,
    location: 'Generated by EasyExplorer',
    description: 'Synced itinerary event',
  });

  if (error) throw error;
  return value;
}

module.exports = { createEvent };
